"""
config.py
Application settings loaded from environment variables / .env file.
Changing DATABASE_URL to a PostgreSQL connection string is all that is needed
to migrate away from SQLite.
"""
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # ── Database ──────────────────────────────────────────────────────────────
    DATABASE_URL: str = "sqlite:///./hospital.db"

    # ── JWT ───────────────────────────────────────────────────────────────────
    SECRET_KEY: str = "change-this-secret-key-before-any-real-deployment"
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
    REFRESH_TOKEN_EXPIRE_DAYS: int = 7

    # ── App ───────────────────────────────────────────────────────────────────
    APP_TITLE: str = "Hospital Information & Workflow Network"
    APP_VERSION: str = "1.0.0-prototype"
    DEBUG: bool = True

    # ── CORS ──────────────────────────────────────────────────────────────────
    ALLOWED_ORIGINS: list[str] = ["http://localhost:3000", "http://127.0.0.1:3000"]

    # ── ML Disclaimer ─────────────────────────────────────────────────────────
    # This constant is stored alongside every ML prediction in the database and
    # returned in every ML API response. It must never be removed.
    ML_DISCLAIMER: str = (
        "⚠️ SYNTHETIC PROTOTYPE PREDICTION — This output was generated by a "
        "machine learning model trained on entirely synthetic data. It does not "
        "represent a medical diagnosis, clinical assessment, or screening result. "
        "It is shown for educational and demonstration purposes only."
    )

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")


settings = Settings()
